Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-20.04"
  c.vm.hostname = "wordpress-app-ubuntu-2004.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/Yanneth/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-chefWP-VAG-wordpress-app-ubuntu-2004-dd167541-28f1-4edb-b0d2-d9efcb065b8d"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
